name: Setup
inputs:
  python-version:
    required: true
    type: string
runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@eaece33b58aff8c48fd301b6c3c188155142fdd3 # v8.2.0
      with:
        enable-cache: true
        python-version: ${{ inputs.python-version }}
