name: Setup
inputs:
  python-version:
    required: true
    type: string
runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        enable-cache: true
        python-version: ${{ inputs.python-version }}
