blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/robotsix/robotsix-modules/discussions
    about: Please ask questions in GitHub Discussions
  - name: Contributing guide
    url: https://github.com/robotsix/robotsix-modules/blob/main/CONTRIBUTING.md
    about: Read the contributing guidelines before opening an issue
