name: Dependabot auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/dependabot-auto-merge.yml@9ea2955d11f3d595a7a812feff99ae0eea8240c1  # main
