name: Docs

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    permissions:
      contents: read  # needed to checkout the repo
      pages: write  # needed to deploy to GitHub Pages
      id-token: write  # needed for OIDC to deploy to Pages
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/python-docs.yml@5cd8c1facb02299da618979e7a55f1953f9c075a
