name: Lint Workflows

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/lint-workflows.yml@d2a2353830cf211a9f18f3585085016766294dff  # main
    with:
      run-actionlint: true
      run-zizmor: true
