name: Lint Workflows

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/lint-workflows.yml@86dae89b637dad27ddba0aaa5f9430e083288365  # main
    with:
      run-actionlint: true
      run-zizmor: true
