name: Publish to PyPI

on:
  release:
    types: [published]

permissions: {}

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    uses: damien-robotsix/robotsix-github-workflows/.github/workflows/python-release.yml@5cd8c1facb02299da618979e7a55f1953f9c075a
    with:
      github-release: true
    secrets: inherit
