name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  release:
    uses: damien-robotsix/robotsix-mill/.github/workflows/python-release.yml@main
    with:
      github-release: true
    secrets: inherit
